class QuranSurah {
  final int number;
  final String nameAr;
  final String nameEn;
  final int verses;

  const QuranSurah({
    required this.number,
    required this.nameAr,
    required this.nameEn,
    required this.verses,
  });
}

const List<QuranSurah> quranSurahs = [
  QuranSurah(number: 1, nameAr: 'الفاتحة', nameEn: 'Al-Fatihah', verses: 7),
  QuranSurah(number: 2, nameAr: 'البقرة', nameEn: 'Al-Baqarah', verses: 286),
  QuranSurah(number: 3, nameAr: 'آل عمران', nameEn: 'Aal-E-Imran', verses: 200),
  QuranSurah(number: 4, nameAr: 'النساء', nameEn: 'An-Nisa', verses: 176),
  QuranSurah(number: 5, nameAr: 'المائدة', nameEn: 'Al-Ma’idah', verses: 120),
  QuranSurah(number: 6, nameAr: 'الأنعام', nameEn: 'Al-An’am', verses: 165),
  QuranSurah(number: 7, nameAr: 'الأعراف', nameEn: 'Al-A’raf', verses: 206),
  QuranSurah(number: 8, nameAr: 'الأنفال', nameEn: 'Al-Anfal', verses: 75),
  QuranSurah(number: 9, nameAr: 'التوبة', nameEn: 'At-Tawbah', verses: 129),
  QuranSurah(number: 10, nameAr: 'يونس', nameEn: 'Yunus', verses: 109),
  QuranSurah(number: 11, nameAr: 'هود', nameEn: 'Hud', verses: 123),
  QuranSurah(number: 12, nameAr: 'يوسف', nameEn: 'Yusuf', verses: 111),
  QuranSurah(number: 13, nameAr: 'الرعد', nameEn: 'Ar-Ra’d', verses: 43),
  QuranSurah(number: 14, nameAr: 'إبراهيم', nameEn: 'Ibrahim', verses: 52),
  QuranSurah(number: 15, nameAr: 'الحجر', nameEn: 'Al-Hijr', verses: 99),
  QuranSurah(number: 16, nameAr: 'النحل', nameEn: 'An-Nahl', verses: 128),
  QuranSurah(number: 17, nameAr: 'الإسراء', nameEn: 'Al-Isra', verses: 111),
  QuranSurah(number: 18, nameAr: 'الكهف', nameEn: 'Al-Kahf', verses: 110),
  QuranSurah(number: 19, nameAr: 'مريم', nameEn: 'Maryam', verses: 98),
  QuranSurah(number: 20, nameAr: 'طه', nameEn: 'Ta-Ha', verses: 135),
  QuranSurah(number: 21, nameAr: 'الأنبياء', nameEn: 'Al-Anbiya', verses: 112),
  QuranSurah(number: 22, nameAr: 'الحج', nameEn: 'Al-Hajj', verses: 78),
  QuranSurah(number: 23, nameAr: 'المؤمنون', nameEn: 'Al-Mu’minun', verses: 118),
  QuranSurah(number: 24, nameAr: 'النور', nameEn: 'An-Nur', verses: 64),
  QuranSurah(number: 25, nameAr: 'الفرقان', nameEn: 'Al-Furqan', verses: 77),
  QuranSurah(number: 26, nameAr: 'الشعراء', nameEn: 'Ash-Shu’ara', verses: 227),
  QuranSurah(number: 27, nameAr: 'النمل', nameEn: 'An-Naml', verses: 93),
  QuranSurah(number: 28, nameAr: 'القصص', nameEn: 'Al-Qasas', verses: 88),
  QuranSurah(number: 29, nameAr: 'العنكبوت', nameEn: 'Al-Ankabut', verses: 69),
  QuranSurah(number: 30, nameAr: 'الروم', nameEn: 'Ar-Rum', verses: 60),
  QuranSurah(number: 31, nameAr: 'لقمان', nameEn: 'Luqman', verses: 34),
  QuranSurah(number: 32, nameAr: 'السجدة', nameEn: 'As-Sajdah', verses: 30),
  QuranSurah(number: 33, nameAr: 'الأحزاب', nameEn: 'Al-Ahzab', verses: 73),
  QuranSurah(number: 34, nameAr: 'سبأ', nameEn: 'Saba', verses: 54),
  QuranSurah(number: 35, nameAr: 'فاطر', nameEn: 'Fatir', verses: 45),
  QuranSurah(number: 36, nameAr: 'يس', nameEn: 'Ya-Sin', verses: 83),
  QuranSurah(number: 37, nameAr: 'الصافات', nameEn: 'As-Saffat', verses: 182),
  QuranSurah(number: 38, nameAr: 'ص', nameEn: 'Sad', verses: 88),
  QuranSurah(number: 39, nameAr: 'الزمر', nameEn: 'Az-Zumar', verses: 75),
  QuranSurah(number: 40, nameAr: 'غافر', nameEn: 'Ghafir', verses: 85),
  QuranSurah(number: 41, nameAr: 'فصلت', nameEn: 'Fussilat', verses: 54),
  QuranSurah(number: 42, nameAr: 'الشورى', nameEn: 'Ash-Shura', verses: 53),
  QuranSurah(number: 43, nameAr: 'الزخرف', nameEn: 'Az-Zukhruf', verses: 89),
  QuranSurah(number: 44, nameAr: 'الدخان', nameEn: 'Ad-Dukhan', verses: 59),
  QuranSurah(number: 45, nameAr: 'الجاثية', nameEn: 'Al-Jathiyah', verses: 37),
  QuranSurah(number: 46, nameAr: 'الأحقاف', nameEn: 'Al-Ahqaf', verses: 35),
  QuranSurah(number: 47, nameAr: 'محمد', nameEn: 'Muhammad', verses: 38),
  QuranSurah(number: 48, nameAr: 'الفتح', nameEn: 'Al-Fath', verses: 29),
  QuranSurah(number: 49, nameAr: 'الحجرات', nameEn: 'Al-Hujurat', verses: 18),
  QuranSurah(number: 50, nameAr: 'ق', nameEn: 'Qaf', verses: 45),
  QuranSurah(number: 51, nameAr: 'الذاريات', nameEn: 'Adh-Dhariyat', verses: 60),
  QuranSurah(number: 52, nameAr: 'الطور', nameEn: 'At-Tur', verses: 49),
  QuranSurah(number: 53, nameAr: 'النجم', nameEn: 'An-Najm', verses: 62),
  QuranSurah(number: 54, nameAr: 'القمر', nameEn: 'Al-Qamar', verses: 55),
  QuranSurah(number: 55, nameAr: 'الرحمن', nameEn: 'Ar-Rahman', verses: 78),
  QuranSurah(number: 56, nameAr: 'الواقعة', nameEn: 'Al-Waqi’ah', verses: 96),
  QuranSurah(number: 57, nameAr: 'الحديد', nameEn: 'Al-Hadid', verses: 29),
  QuranSurah(number: 58, nameAr: 'المجادلة', nameEn: 'Al-Mujadilah', verses: 22),
  QuranSurah(number: 59, nameAr: 'الحشر', nameEn: 'Al-Hashr', verses: 24),
  QuranSurah(number: 60, nameAr: 'الممتحنة', nameEn: 'Al-Mumtahanah', verses: 13),
  QuranSurah(number: 61, nameAr: 'الصف', nameEn: 'As-Saff', verses: 14),
  QuranSurah(number: 62, nameAr: 'الجمعة', nameEn: 'Al-Jumu’ah', verses: 11),
  QuranSurah(number: 63, nameAr: 'المنافقون', nameEn: 'Al-Munafiqun', verses: 11),
  QuranSurah(number: 64, nameAr: 'التغابن', nameEn: 'At-Taghabun', verses: 18),
  QuranSurah(number: 65, nameAr: 'الطلاق', nameEn: 'At-Talaq', verses: 12),
  QuranSurah(number: 66, nameAr: 'التحريم', nameEn: 'At-Tahrim', verses: 12),
  QuranSurah(number: 67, nameAr: 'الملك', nameEn: 'Al-Mulk', verses: 30),
  QuranSurah(number: 68, nameAr: 'القلم', nameEn: 'Al-Qalam', verses: 52),
  QuranSurah(number: 69, nameAr: 'الحاقة', nameEn: 'Al-Haqqah', verses: 52),
  QuranSurah(number: 70, nameAr: 'المعارج', nameEn: 'Al-Ma’arij', verses: 44),
  QuranSurah(number: 71, nameAr: 'نوح', nameEn: 'Nuh', verses: 28),
  QuranSurah(number: 72, nameAr: 'الجن', nameEn: 'Al-Jinn', verses: 28),
  QuranSurah(number: 73, nameAr: 'المزمل', nameEn: 'Al-Muzzammil', verses: 20),
  QuranSurah(number: 74, nameAr: 'المدثر', nameEn: 'Al-Muddaththir', verses: 56),
  QuranSurah(number: 75, nameAr: 'القيامة', nameEn: 'Al-Qiyamah', verses: 40),
  QuranSurah(number: 76, nameAr: 'الإنسان', nameEn: 'Al-Insan', verses: 31),
  QuranSurah(number: 77, nameAr: 'المرسلات', nameEn: 'Al-Mursalat', verses: 50),
  QuranSurah(number: 78, nameAr: 'النبأ', nameEn: 'An-Naba', verses: 40),
  QuranSurah(number: 79, nameAr: 'النازعات', nameEn: 'An-Nazi’at', verses: 46),
  QuranSurah(number: 80, nameAr: 'عبس', nameEn: 'Abasa', verses: 42),
  QuranSurah(number: 81, nameAr: 'التكوير', nameEn: 'At-Takwir', verses: 29),
  QuranSurah(number: 82, nameAr: 'الانفطار', nameEn: 'Al-Infitar', verses: 19),
  QuranSurah(number: 83, nameAr: 'المطففين', nameEn: 'Al-Mutaffifin', verses: 36),
  QuranSurah(number: 84, nameAr: 'الانشقاق', nameEn: 'Al-Inshiqaq', verses: 25),
  QuranSurah(number: 85, nameAr: 'البروج', nameEn: 'Al-Buruj', verses: 22),
  QuranSurah(number: 86, nameAr: 'الطارق', nameEn: 'At-Tariq', verses: 17),
  QuranSurah(number: 87, nameAr: 'الأعلى', nameEn: 'Al-A’la', verses: 19),
  QuranSurah(number: 88, nameAr: 'الغاشية', nameEn: 'Al-Ghashiyah', verses: 26),
  QuranSurah(number: 89, nameAr: 'الفجر', nameEn: 'Al-Fajr', verses: 30),
  QuranSurah(number: 90, nameAr: 'البلد', nameEn: 'Al-Balad', verses: 20),
  QuranSurah(number: 91, nameAr: 'الشمس', nameEn: 'Ash-Shams', verses: 15),
  QuranSurah(number: 92, nameAr: 'الليل', nameEn: 'Al-Layl', verses: 21),
  QuranSurah(number: 93, nameAr: 'الضحى', nameEn: 'Ad-Duha', verses: 11),
  QuranSurah(number: 94, nameAr: 'الشرح', nameEn: 'Ash-Sharh', verses: 8),
  QuranSurah(number: 95, nameAr: 'التين', nameEn: 'At-Tin', verses: 8),
  QuranSurah(number: 96, nameAr: 'العلق', nameEn: 'Al-Alaq', verses: 19),
  QuranSurah(number: 97, nameAr: 'القدر', nameEn: 'Al-Qadr', verses: 5),
  QuranSurah(number: 98, nameAr: 'البينة', nameEn: 'Al-Bayyinah', verses: 8),
  QuranSurah(number: 99, nameAr: 'الزلزلة', nameEn: 'Az-Zalzalah', verses: 8),
  QuranSurah(number: 100, nameAr: 'العاديات', nameEn: 'Al-Adiyat', verses: 11),
  QuranSurah(number: 101, nameAr: 'القارعة', nameEn: 'Al-Qari’ah', verses: 11),
  QuranSurah(number: 102, nameAr: 'التكاثر', nameEn: 'At-Takathur', verses: 8),
  QuranSurah(number: 103, nameAr: 'العصر', nameEn: 'Al-Asr', verses: 3),
  QuranSurah(number: 104, nameAr: 'الهمزة', nameEn: 'Al-Humazah', verses: 9),
  QuranSurah(number: 105, nameAr: 'الفيل', nameEn: 'Al-Fil', verses: 5),
  QuranSurah(number: 106, nameAr: 'قريش', nameEn: 'Quraysh', verses: 4),
  QuranSurah(number: 107, nameAr: 'الماعون', nameEn: 'Al-Ma’un', verses: 7),
  QuranSurah(number: 108, nameAr: 'الكوثر', nameEn: 'Al-Kawthar', verses: 3),
  QuranSurah(number: 109, nameAr: 'الكافرون', nameEn: 'Al-Kafirun', verses: 6),
  QuranSurah(number: 110, nameAr: 'النصر', nameEn: 'An-Nasr', verses: 3),
  QuranSurah(number: 111, nameAr: 'المسد', nameEn: 'Al-Masad', verses: 5),
  QuranSurah(number: 112, nameAr: 'الإخلاص', nameEn: 'Al-Ikhlas', verses: 4),
  QuranSurah(number: 113, nameAr: 'الفلق', nameEn: 'Al-Falaq', verses: 5),
  QuranSurah(number: 114, nameAr: 'الناس', nameEn: 'An-Nas', verses: 6),
];
